apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicegraph-flink.restServiceName" . }}
  labels:
    {{- include "servicegraph-flink.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8081
      targetPort: rest
      protocol: TCP
  selector:
    {{- include "servicegraph-flink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobmanager
