{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicegraph-flink.serviceAccountName" . }}
  labels:
    {{- include "servicegraph-flink.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
