{{- if and .Values.storage.createClaim (not .Values.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "servicegraph-flink.claimName" . }}
  labels:
    {{- include "servicegraph-flink.labels" . | nindent 4 }}
  {{- if .Values.storage.retainClaim }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
