apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicegraph-collector.fullname" . }}-backend-headless
  labels:
    {{- include "servicegraph-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: servicegraph-backend
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "servicegraph-collector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: servicegraph-backend
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
