apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicegraph-collector.fullname" . }}-router
  labels:
    {{- include "servicegraph-collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: router
  {{- with .Values.router.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.router.service.type }}
  selector:
    {{- include "servicegraph-collector.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: router
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
