apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicegraph-gremlin.fullname" . }}
  labels:
    {{- include "servicegraph-gremlin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: gremlin
      port: {{ .Values.service.port }}
      targetPort: gremlin
  selector:
    app.kubernetes.io/name: {{ include "servicegraph-gremlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
