{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicegraph-arangodb.secretName" . }}
  labels:
    {{- include "servicegraph-arangodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.passwordKey }}: {{ required "auth.rootPassword is required when auth.existingSecret is empty" .Values.auth.rootPassword | quote }}
{{- end }}
