{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicegraph-ui.serviceAccountName" . }}
  labels:
    {{- include "servicegraph-ui.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
