apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: servicegraph-flink-jobmanager
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servicegraph-flink
      app.kubernetes.io/component: jobmanager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: servicegraph-flink-taskmanager
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: servicegraph-flink
      app.kubernetes.io/component: taskmanager
