apiVersion: v1
kind: Secret
metadata:
  name: servicegraph-kafka-auth
  namespace: team
type: Opaque
stringData:
  username: replace-me
  password: replace-me
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_INTERNAL_KAFKA_CA
    -----END CERTIFICATE-----
