apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team
resources:
  - rbac.yaml
  - storage.yaml
  - flink.yaml
  - collector.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
configMapGenerator:
  - name: servicegraph-flink-config
    files:
      - flink-conf.yaml
  - name: servicegraph-job-submitter
    files:
      - submit-job.sh
  - name: servicegraph-otelcol-config
    files:
      - config.yaml=otelcol.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: extended-otel-semconv
    app.kubernetes.io/managed-by: kustomize
