apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicegraph-flink
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicegraph-otelcol
  labels:
    app.kubernetes.io/name: servicegraph-otelcol
    app.kubernetes.io/part-of: extended-otel-semconv
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicegraph-flink-ha
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicegraph-flink-ha
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
subjects:
  - kind: ServiceAccount
    name: servicegraph-flink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servicegraph-flink-ha
