apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servicegraph-flink-state
  labels:
    app.kubernetes.io/name: servicegraph-flink
    app.kubernetes.io/part-of: extended-otel-semconv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: basic
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servicegraph-otelcol-queue
  labels:
    app.kubernetes.io/name: servicegraph-otelcol
    app.kubernetes.io/part-of: extended-otel-semconv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: basic
  resources:
    requests:
      storage: 10Gi
